### ISSUE TITLE
Project ideas, SusHack 3

### ISSUE THREAD

**Issue by omgmog** [sushack/sushack.github.io#35]
Share your project ideas for SusHack 3 here.

Feel free to look to the [SusHack 2](https://github.com/sushack/sushack.github.io/issues/18) project ideas for inspiration!

**Comment by thiseldo** [comment]
Has anyone done anything with measuring noise levels across a town/city and crating a realtime noise level heatmap/noisemap? There are some very sensitive MEMS microphones around that could be hooked up to an Arduino/Raspberry Pi/ESP8266 to produce a sound level value feeding back into a backend/cloud system. Having multiple sensors throughout could help determine which areas have a higher background noise level (hum from traffic etc) and what times of the day there are peak noise levels (e.g. planes, helicopters flying over, trains, schools going in/coming out, loud neighbours etc).

**Comment by omgmog** [comment]
Would be a really cool thing to visualise, but I wonder if there would be privacy concerns, and issues (presumably as you've had with the oxfloodnet sensors) about connectivity?

Could think of a more localised version of this maybe, and plot the volume levels in a building or something, to help people find the best place to get some "quiet time"

**Comment by LuRsT** [comment]
They've done something like this for libraries in oxford, but I too would be very wary of privacy issues...

**Comment by thiseldo** [comment]
What do you mean about privacy issues? People say this but dont give specifics, its like they just want to quote buzzwords!
These would be similar to monitoring temperature or air quality levels in an area, not recording anything so don't see any privacy issues at all.

**Comment by omgmog** [comment]
We know that, but I imagine your average lay-person would assume that a device capable of picking up sound could be used for more privacy-breaching recording means.

**Comment by LuRsT** [comment]
@thiseldo, what do I mean about privacy issues? Do you really think that privacy is just a buzzword?

The fact that those particular devices aren't recording "anything", still means that you want recording devices on public places recording sounds produced by people *without* their consent, and even thought they aren't recording "anything" as you say, who controls which devices are recording? How can you assure people that those are the only devices recording and nothing else?

The issue here is *consent*, if you have it, that's cool, so doing this on one day in an area that people know that they are being recorded it's OK by me.

**Comment by simonredding** [comment]
Perhaps the flood thing is something that's been done, but how about using some of the newer flood open data to visualise risk & protection to communities, linked to community telemetry & monitoring? So for example, it would be good if a single system can say:
"The flood was here in 1957 and here in 1978, the modelled risk for your house is low because you're protected by this defence. Here are critical assets that you as a community need to make sure are in good condition (e.g. storm drain trash screens aren't blocked up). Here's your community monitoring network that shows that you're not currently at risk."

**Comment by simonredding** [comment]
Perhaps there's also an angle about introducing sensor network approaches like the TVWS platform to other things apart from flooding.  For example "when do the combined sewer overflow systems dump into the local river" could be done with the existing sensors; "is this trash screen blocked" would require low cost cameras & image analysis; basic oxygen demand sensors could monitor river pollution.

**Comment by omgmog** [comment]
Another idea:

Not particularly sustainability related (though it could be made to be related with a good data source!), I'm interested in hacking around with real-space motion/orientation and mobile phones, using the Google Cardboard stuff (https://www.google.com/get/cardboard/). 

So I've ordered a couple of Google Cardboard kits from Amazon, one cardboard, one plastic, they should arrive in plenty of time.

Regarding making this a "sustainability" thing, we could do something like mashing up google street view and some map data source? Oxford Flood Network in 3d?! who knows, should be fun.

In the mean time, I'll probably brush up on my device orientation knowledge, and anybody who would like to join in should too! (@benfoxall?)

**Comment by LuRsT** [comment]
Sounds great! I'd like to check those things!

**Comment by benfoxall** [comment]
@omgmog AWESOME.  I've just ordered a cardboard too!  What ever we end up doing; I'm 100% into it.  Shall we create another issue to throw down ideas?

:sparkles: **C-A-R-D-B-O-A-R-D** :sparkles:

**Comment by omgmog** [comment]
@benfoxall #40

**Comment by AverageMarcus** [comment]
Just though, I have a box full of [Physical Web](https://google.github.io/physical-web/) beacons. Anyone got any ideas for these?

**Comment by xmakina** [comment]
@averagemarcus I'd definitely be interested in coming up with some ideas for the physical web.

**Comment by AverageMarcus** [comment]
:+1: Awesome. I'll bring them along with me.

**Comment by benfoxall** [comment]
### [Pusher](https://pusher.com/) have offered to sponsor [summer of hacks](http://summerofhacks.io/) :rocket:

> Pusher is a hosted service for quickly and easily adding realtime features into web and mobile applications. We're used for all sorts of features such as notifications, game movements, chat, live data feeds and much more. Our aim is to take away the headache of configuring realtime infrastructure so that developers can concentrate on making awesome stuff.

For SusHack, we have a $300 credit available. @omgmog has the code if you want to grab it.

We've got some swag arriving soon (not soon enough for tomorrow unfortunately) - though I'll set some aside for anyone who ends up using the service.

---

@thiseldo are you still interested in doing a noise pollution monitor?  Pusher might fit this well if so.

**Comment by LuRsT** [comment]
That's awesome @benfoxall!

**Comment by omgmog** [comment]
Some pusher goodness for my #40 cardboard ideas would be very cool!
